import { initializeApp } from "firebase/app";

import * as dotenv from "dotenv";
dotenv.config();

const firebaseConfig = {
  apiKey: process.env.API_KEY,
  authDomain: process.env.AUTH_DOMAIN,
  databaseURL: process.env.DATABASE_URL,
  projectId: process.env.PROJECT_ID,
  storageBucket: process.env.STORAGE_BUCKET,
  messagingSenderId: process.env.MESSAGING_SENDER_ID,
  appId: process.env.APP_ID,
  measurementId: process.env.MEASUREMENT_ID,
};

// Initialize Firebase
export const app = initializeApp(firebaseConfig);

// get All users when there is any changes in users database
// export let users = [];
// export function getAllUsers() {
//   onValue(ref(db, "user/"), async (snapshot) => {
//     let users = snapshot.val();
//   });
// }

// //update user by given id,
// export async function updateUser(userId, name, email, imgUrl, age) {
//   try {
//     const userIdRef = ref(db, "user/" + userId);
//     await update(userIdRef, {
//       username: name,
//       email: email,
//       profile_picture: imgUrl,
//       age: age,
//     });
//     return "User Update Successfully";
//   } catch (err) {
//     return err;
//   }
// }

// //remove user by given id,
// export async function removeUser(userId) {
//   try {
//     const userIdRef = ref(db, "user/" + userId);
//     await remove(userIdRef);
//     return "User Deleted Successfully";
//   } catch (error) {
//     return error;
//   }
// }

// // get User by given id
// export function getUser(userId) {
//   const userRef = ref(db, "user/" + userId);
//   onValue(userRef, (snapshot) => {
//     const data = snapshot.val();
//     console.log({ data });
//   });
// }

// //add new User by random id
// export function addUserByRandomId(name, email, imgUrl, age) {
//   const userRef = ref(db, "user/");
//   //key generated by push is based on timestamp
//   const newUserRef = push(userRef);
//   set(newUserRef, {
//     username: name,
//     email: email,
//     profile_picture: imgUrl,
//     age: age,
//   });
// }

// // // get User age by id in Realtime
// // function getUserAgeById(userId) {
// //   const ageRef = ref(db, "user/" + userId + "/age");
// //   onValue(ageRef, (snapshot) => {
// //     const data = snapshot.val();
// //     console.log({ data });
// //   });
// // }

// // //get all users when new user is added
// // function getAllUsersAfterNewUserAdded() {
// //   const userRef = ref(db, "user/");
// //   onChildAdded(userRef, (data) => {
// //     console.log("------------------");
// //     console.log("id:" + data.key);
// //     console.log(data.val());
// //     console.log("------------------");
// //   });
// // }

// // //get user which is updated in users collection
// // function getUsersAfterUpdated() {
// //   const userRef = ref(db, "user/");
// //   onChildChanged(userRef, (data) => {
// //     console.log("------------------");
// //     console.log("id:" + data.key);
// //     console.log(data.val());
// //     console.log("------------------");
// //   });
// // }
